package com.cydeo.test.day11_Webtables_Utilities;

public class TableLocators {


    /*

P1_ WRITE A LOCATOR THAT RETURNS THE TABLE 1 ITSELF
//table[@id='table1']

P2_ WRITE A LOCATOR THAT RETURNS ALL ROWS INSIDE OF TABLE 1

P3_ WRITE A LOCATOR THAT RETURNS ALL OF THE ROWS INSIDE OF BODY - TABLE 1

P4_ WRITE A LOCATOR THAT RETURNS ONLY 3RD ROW IN THE BODY

P5_ WRITE A LOCATOR THAT RETURNS ALL OF THE CELLS IN ALL OF THE ROW (IN BODY)

P6_ WRITE A LOCATOR THAT RETURNS ALL OF THE FIRST NAMES FROM TABLE
     */
}
